#+title: Readme

* Org Todoist: What is it?
Org todoist is an emacs package for syncing [[https://orgmode.org/][org mode todos]] with [[https://todoist.com/][Todoist]]
* Why?
Org mode is an excellent planning and note-taking tool, but struggles in a few areas:

- Collaboration with non-neckbeards
- Mobile app features / availability (shoutout to [[https://github.com/orgzly-revived/orgzly-android-revived][Orgzly for their great android app]])
- Sync between devices (I personally use [[https://syncthing.net/][Syncthing]] which works well, but will often have conflicts when adding from the widget)

Todoist fills these gaps and, more importantly, my wife uses it.

There is currently [[https://github.com/abrochard/emacs-todoist][another excellent integration]] for org-mode and todoist, but it takes a fundamentally different approach (stateless on-demand regeneration with the [[https://developer.todoist.com/rest/v2/#overview][REST API]] vs stateful syncing with the [[https://developer.todoist.com/sync/v9/#overview][sync API]] that can be queried by [[https://github.com/orgzly-revived/orgzly-android-revived][Orgzly]] on mobile and buffer creation with org.el vs [[https://orgmode.org/worg/dev/org-element-api.html][org-element-api]]).
* Features

** Notes
- Once a task has been permanently deleted in Todoist, changing the TODO state in org will be reset back to org-todoist-deleted-keyword on next sync. Todoist does not support reviving permanently deleted tasks.
- Comments on subtasks are added to both the root task and the subtask on Todoist, which is reflected here.
* Roadmap

Features are read only (unidirectional sync) unless otherwise noted.

- [X] Generate skeleton todoist buffer on-demand
  - [X] Projects
  - [X] Sections
  - [X] Tasks
  - [X] Collaborators
- [-] Add essential task items
  - [X] TODO status
  - [X] Tags/labels
  - [X] Scheduled
  - [X] Deadline
  - [X] Completed (currently in utc)
  - [X] Priority
  - [X] Assignee
  - [X] Skip properties to reduce drawer size
  - [-] Recurring tasks (has basic support, missing many natural language recurring due dates & only updates with item_update and not item_close)
  - [X] Subtask support
  - [ ] Quick add
- [-] Implement sync updates
  - [X] Manual sync read updates
  - [ ] Automated sync read updates(?)
  - [-] Push updates
    - [X] TODO state
    - [X] Title
    - [X] Scheduled
    - [X] Deadline
    - [X] Completed
    - [X] Description
    - [-] Comments
      - [-] Item comments
        - [X] Add
        - [ ] Sort by time added
        - [ ] Update
        - [ ] Delete
        - [-] Notify other users*
      - [ ] Project comments
        - [ ] Add
        - [ ] Update
        - [ ] Delete
        - [ ] Notify other users
    - [X] Effort
    - [X] Priority
    - [X] Labels
    - [X] Assigned to
    - [X] Task refiling
      - [X] Refile to section
      - [X] Refile to project
    - [X] New tasks
    - [X] New sections
    - [X] New projects
    - [X] Refile section to new project
    - [X] Deletions
      - [X] Sections
      - [X] Projects
      - [X] Tasks (pull from remote)
      - [X] Tasks (local)
- [-] Add non-essential task items
  - [X] Datetime for scheduled / deadline (time of day)
  - [X] Effort/Duration
  - [ ] Better assignee filtering in agenda
  - [ ] Subproject support
- [ ] Support org linking by id (rename current id property?)
- [-] Essential project packaging
  - [X] Provide functions in org-todoist.el file
  - [ ] Autoloads
  - [X] Remove dev local hardcoded paths
  - [ ] Better README
    - [ ] Clearer feature explanation
    - [ ] Examples
    - [ ] How to use
- [ ] Implement low priority items
  - [ ] Markdown description support
  - [ ] Better logbook syncing (I currently am using syncthing for this)
    - [ ] Sync via Todoist?
* Not currently planning to implement
- File attachments
- Filters (use org agenda for this)
* Disclaimer
This package is not associated with [[https://doist.com/][Doist]] or [[https://orgmode.org/][Org]]
* Author's notes
This is my first major elisp project, so I am almost certainly missing some best practices and useful tools. If you have any knowledge to share or want to contribute, please reach out, create an issue, or open a PR!
