name: check
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
        ignore_warnings:
          - true
    steps:
      - uses: actions/checkout@v4

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Lint
        uses: leotaku/elisp-check@master
        with:
          file: "org-todoist.el"
          ignore_warnings: ${{ matrix.ignore_warnings }}
          check: package-lint

      - name: Test
        uses: leotaku/elisp-check@master
        with:
          check: ert
          file: "test.el"
          ignore_warnings: ${{ matrix.ignore_warnings }}
